from pathlib import Path


# =========================
# Paths
# =========================

REPO_ROOT = Path(__file__).resolve().parent
RUNS_DIR = REPO_ROOT / "runs"
CACHE_DIR = REPO_ROOT / "data" / "stablewm"


# =========================
# Training Run
# =========================

TRAIN_DATASET = "pusht"
OUTPUT_MODEL_NAME = "lewm"
RUN_NAME = None

TRAIN_SPLIT = 0.9
SEED = 3072

IMG_SIZE = 224
PATCH_SIZE = 14
ENCODER_SCALE = "tiny"

MAX_EPOCHS = 13
ACCELERATOR = "gpu"
DEVICES = "auto"
PRECISION = "fp16"
GRADIENT_CLIP_VAL = 1.0
USE_TORCH_COMPILE = True

BATCH_SIZE = 16
NUM_WORKERS = 6
PERSISTENT_WORKERS = True
PREFETCH_FACTOR = 3
PIN_MEMORY = True

OPTIMIZER_NAME = "AdamW"
LEARNING_RATE = 5e-5
WEIGHT_DECAY = 1e-3

CONSOLE_EVERY_STEPS = 20
WRITE_EVERY_STEPS = 100
PLOT_EVERY_STEPS = 100
PLOT_EVERY_EPOCHS = 1
SAVE_TSV = True

HISTORY_SIZE = 3
NUM_PREDS = 1
EMBED_DIM = 192
ACTION_DIM = 2
USE_LEARNED_ACTIONS = True

NUM_CODES = 8
CODEBOOK_BETA = 0.25

PREDICTOR_DEPTH = 6
PREDICTOR_HEADS = 16
PREDICTOR_MLP_DIM = 2048
PREDICTOR_DIM_HEAD = 64
PREDICTOR_DROPOUT = 0.1
PREDICTOR_EMB_DROPOUT = 0.0

INVERSE_DYNAMICS_DEPTH = 4
INVERSE_DYNAMICS_HEADS = 8
INVERSE_DYNAMICS_MLP_DIM = 1024
INVERSE_DYNAMICS_DIM_HEAD = 64
INVERSE_DYNAMICS_DROPOUT = 0.1
INVERSE_DYNAMICS_EMB_DROPOUT = 0.0

SIGREG_WEIGHT = 0.09
SIGREG_KNOTS = 17
SIGREG_NUM_PROJ = 1024

CODEBOOK_LOSS_WEIGHT = 1.0
COMMITMENT_LOSS_WEIGHT = 1.0


# =========================
# Active Train Dataset
# Change these directly.
# =========================

DATASET_NAME = "pusht_expert_train"
DATASET_FRAMESKIP = 5
DATASET_KEYS_TO_LOAD = ["pixels", "action", "proprio", "state"]
DATASET_KEYS_TO_CACHE = ["action", "proprio", "state"]
DATASET_KEYS_TO_MERGE = {}

# Other examples:
# DATASET_NAME = "tworoom"
# DATASET_KEYS_TO_LOAD = ["pixels", "action", "proprio"]
# DATASET_KEYS_TO_CACHE = ["action", "proprio"]

# DATASET_NAME = "reacher"
# DATASET_KEYS_TO_LOAD = ["pixels", "action", "observation"]
# DATASET_KEYS_TO_CACHE = ["action", "observation"]

# DATASET_NAME = "ogbench/cube_single_expert"
# DATASET_KEYS_TO_LOAD = ["pixels", "action", "observation"]
# DATASET_KEYS_TO_CACHE = ["action", "observation"]
# DATASET_KEYS_TO_MERGE = {"proprio": "proprio"}


# =========================
# Decoder Training
# =========================

DECODER_SOURCE_CHECKPOINT = None
DECODER_SOURCE_MODEL_MODE = "train"
DECODER_RESUME_CHECKPOINT = None

DECODER_RUN_NAME = "decoder"
DECODER_MAX_EPOCHS = 13
DECODER_BATCH_SIZE = 16
DECODER_NUM_WORKERS = 6
DECODER_PERSISTENT_WORKERS = True
DECODER_PREFETCH_FACTOR = 3
DECODER_PIN_MEMORY = True

DECODER_LEARNING_RATE = 1e-4
DECODER_WEIGHT_DECAY = 1e-4
DECODER_GRADIENT_CLIP_VAL = 1.0

DECODER_EMBED_DIM = EMBED_DIM
DECODER_BASE_CHANNELS = 256

DECODER_CONSOLE_EVERY_STEPS = 20
DECODER_WRITE_EVERY_STEPS = 100
DECODER_PLOT_EVERY_STEPS = 100
DECODER_PLOT_EVERY_EPOCHS = 1
DECODER_SAVE_TSV = True

DECODER_NUM_VIS_SAMPLES = 4
DECODER_TOPK_FRACTION = 0.025


# =========================
# TAESD Adapter Training
# =========================

TAESD_SOURCE_CHECKPOINT = None
TAESD_SOURCE_MODEL_MODE = "train"
TAESD_MODEL_NAME = "madebyollin/taesd"

TAESD_RUN_NAME = "taesd-adapter"
TAESD_MAX_EPOCHS = 13
TAESD_BATCH_SIZE = 16
TAESD_NUM_WORKERS = 6
TAESD_PERSISTENT_WORKERS = True
TAESD_PREFETCH_FACTOR = 3
TAESD_PIN_MEMORY = True

TAESD_LEARNING_RATE = 1e-4
TAESD_WEIGHT_DECAY = 1e-4
TAESD_GRADIENT_CLIP_VAL = 1.0

TAESD_LATENT_CHANNELS = 4
TAESD_LATENT_SIZE = 28
TAESD_ADAPTER_HIDDEN_DIM = 2048

TAESD_CONSOLE_EVERY_STEPS = 20
TAESD_WRITE_EVERY_STEPS = 100
TAESD_PLOT_EVERY_STEPS = 100
TAESD_PLOT_EVERY_EPOCHS = 1
TAESD_SAVE_TSV = True

TAESD_NUM_VIS_SAMPLES = 4
TAESD_LATENT_LOSS_WEIGHT = 1.0
TAESD_PIXEL_LOSS_WEIGHT = 0.25


# =========================
# Action Translator Training
# =========================

TRANSLATOR_SOURCE_CHECKPOINT = None
TRANSLATOR_SOURCE_MODEL_MODE = "train"

TRANSLATOR_RUN_NAME = "action-translator"
TRANSLATOR_MAX_EPOCHS = 13
TRANSLATOR_BATCH_SIZE = 16
TRANSLATOR_NUM_WORKERS = 6
TRANSLATOR_PERSISTENT_WORKERS = True
TRANSLATOR_PREFETCH_FACTOR = 3
TRANSLATOR_PIN_MEMORY = True

TRANSLATOR_LEARNING_RATE = 1e-4
TRANSLATOR_WEIGHT_DECAY = 1e-4
TRANSLATOR_GRADIENT_CLIP_VAL = 1.0

TRANSLATOR_HIDDEN_DIM = 256

TRANSLATOR_CONSOLE_EVERY_STEPS = 20
TRANSLATOR_WRITE_EVERY_STEPS = 100
TRANSLATOR_PLOT_EVERY_STEPS = 100
TRANSLATOR_PLOT_EVERY_EPOCHS = 1
TRANSLATOR_SAVE_TSV = True

TRANSLATOR_NUM_VIS_SAMPLES = 4
TRANSLATOR_MSE_WEIGHT = 1.0
TRANSLATOR_ANALYSIS_SAMPLES = 2048
TRANSLATOR_ANALYSIS_RUN_NAME = "action-code-analysis"


# =========================
# Evaluation
# =========================

EVAL_POLICY = "random"
EVAL_SEED = 42
EVAL_NUM = 50
EVAL_GOAL_OFFSET_STEPS = 25
EVAL_BUDGET = 50
EVAL_IMG_SIZE = 224
EVAL_USE_ACTION_TRANSLATOR = True
EVAL_TRANSLATOR_CHECKPOINT = None

PLAN_HORIZON = 5
PLAN_RECEDING_HORIZON = 5
PLAN_ACTION_BLOCK = 5

SOLVER_TYPE = "cem"
SOLVER_BATCH_SIZE = 1
SOLVER_NUM_SAMPLES = 300
SOLVER_N_STEPS = 30
SOLVER_DEVICE = "cuda"
SOLVER_SEED = 42
SOLVER_VAR_SCALE = 1.0
SOLVER_TOPK = 30
SOLVER_ACTION_NOISE = 0.0
SOLVER_OPTIMIZER_CLS = "torch.optim.AdamW"
SOLVER_OPTIMIZER_KWARGS = {"lr": 0.1}


# =========================
# Active Eval Setup
# Change these directly.
# =========================

EVAL_OUTPUT_FILENAME = "pusht_results.txt"

EVAL_WORLD_ENV_NAME = "swm/PushT-v1"
EVAL_WORLD_HISTORY_SIZE = 1
EVAL_WORLD_FRAME_SKIP = 1
EVAL_WORLD_TASK = None
EVAL_WORLD_ENV_TYPE = None
EVAL_WORLD_OB_TYPE = None
EVAL_WORLD_MULTIVIEW = None
EVAL_WORLD_WIDTH = None
EVAL_WORLD_HEIGHT = None
EVAL_WORLD_VISUALIZE_INFO = None
EVAL_WORLD_TERMINATE_AT_GOAL = None

EVAL_DATASET_NAME = "pusht_expert_train"
EVAL_DATASET_KEYS_TO_CACHE = ["action", "proprio", "state"]

EVAL_CALLABLES = [
    {"method": "_set_state", "args": {"state": {"value": "state"}}},
    {"method": "_set_goal_state", "args": {"goal_state": {"value": "goal_state"}}},
]

# Other examples:
# EVAL_OUTPUT_FILENAME = "tworoom_results.txt"
# EVAL_WORLD_ENV_NAME = "swm/TwoRoom-v1"
# EVAL_DATASET_NAME = "tworoom"
# EVAL_DATASET_KEYS_TO_CACHE = ["action", "proprio"]
# EVAL_CALLABLES = [
#     {"method": "_set_state", "args": {"state": {"value": "proprio"}}},
#     {"method": "_set_goal_state", "args": {"goal_state": {"value": "goal_proprio"}}},
# ]

# EVAL_OUTPUT_FILENAME = "dmc_results.txt"
# EVAL_WORLD_ENV_NAME = "swm/ReacherDMControl-v0"
# EVAL_WORLD_TASK = "qpos_match"
# EVAL_DATASET_NAME = "dmc/reacher_random"
# EVAL_DATASET_KEYS_TO_CACHE = ["action"]

# EVAL_OUTPUT_FILENAME = "ogb_cube_results.txt"
# EVAL_WORLD_ENV_NAME = "swm/OGBCube-v0"
# EVAL_WORLD_ENV_TYPE = "single"
# EVAL_WORLD_OB_TYPE = "states"
# EVAL_WORLD_MULTIVIEW = False
# EVAL_WORLD_WIDTH = 224
# EVAL_WORLD_HEIGHT = 224
# EVAL_WORLD_VISUALIZE_INFO = False
# EVAL_WORLD_TERMINATE_AT_GOAL = True
# EVAL_DATASET_NAME = "ogbench/cube_single_expert"
# EVAL_DATASET_KEYS_TO_CACHE = ["action"]
